name: "Npm version and push"
description: "This runs npm version and changes patch, minor or major depending on the commit message contents"

inputs:
  commit_message:
    description: "Commit message"
    required: true
  email:
    description: "Email to be used in commit push"
    required: true
  name:
    description: "Name to be used in commit push"
    required: true

runs:
  using: composite
  steps:
    - name: Fix git config
      shell: bash
      run: |
        git config --global user.name ${{ env.name }}
        git config --global user.email ${{ env.email }}

    - name: Git status
      shell: bash
      run: git status

    - name: Bump version major
      shell: bash
      if: |
        contains(env.commit_message, 'breaking') ||
        contains(env.commit_message, 'feat!') ||
        contains(env.commit_message, 'fix!') ||
        contains(env.commit_message, 'chore!')
      id: major
      run: |
        npm version major
        echo '::set-output name=version::major'

    - name: Bump version minor
      shell: bash
      if: contains(env.commit_message, 'feat') && steps.major.outputs.version != 'major'
      id: minor
      run: |
        npm version minor
        echo '::set-output name=version::minor'

    - name: Bump version patch
      shell: bash
      if: |
        (contains(env.commit_message, 'fix') ||
        contains(env.commit_message, 'chore') ||
        contains(env.commit_message, 'docs') ||
        contains(env.commit_message, 'refactor') ||
        contains(env.commit_message, 'test')) &&
        steps.minor.outputs.version != 'minor' &&
        steps.major.outputs.version != 'major'
      run: npm version patch

    - name: Push version Bump
      shell: bash
      run: git push origin ${{ github.head_ref }}
