name: Terraform apply
description: Terraform apply

inputs:
  google_credentials:
    required: true
    description: Credentials used to authenticate to google

  working_directory:
    required: false
    default: .
    description: The working directory of the terraform file

  terraform_backend_bucket_name:
    required: true
    description: Name of the google cloud bucket

  terraform_plan_filename:
    required: false
    default: terraform.tfstate
    description: Filename of the tfstate file

  terraform_plan_artifact_name:
    required: false
    default: terraform_plan
    description: Artifact name

  download_artifact:
    required: false
    default: false
    description: If an artifact should be downloaded before running terraform apply

runs:
  using: composite

  steps:
    - name: Setup terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform init
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        GOOGLE_CREDENTIALS: ${{ inputs.google_credentials }}
      run: terraform init -backend-config="bucket=${{ inputs.terraform_backend_bucket_name }}"

    - name: Download artifact
      if: inputs.download_artifact == true
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.terraform_plan_artifact_name }}
        path: ${{ inputs.working_directory }}

    - name: Terraform apply
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        GOOGLE_CREDENTIALS: ${{ inputs.google_credentials }}
      run: |
        terraform apply -force -auto-approve -input=false ${{ inputs.terraform_plan_filename }}
