on:
  workflow_call:
    inputs:
      package_path:
        required: true
        description: The path to the package.json file to publish
        type: string
      build_command:
        required: false
        description: Command to build package(s)
        type: string
    secrets:
      NPM_TOKEN:
        required: true
        description: Npm token to use when publishing

permissions:
  contents: write

jobs:
  package-commit-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Npm install
        run: npm ci

      - name: build
        run: npm run build

      - name: Publish package
        uses: JS-DevTools/npm-publish@v1
        with:
          package: "${{ inputs.package_path }}"
          token: ${{ secrets.NPM_TOKEN }}
